spring:
  profiles:
    active: development

---
server:
  contextPath: /uaa
spring:
  profiles: development
eureka:
  instance:
    prefer-ip-address: true
    non-secure-port: 8787
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
server:
  contextPath: /uaa
spring:
  profiles: docker
eureka:
  instance:
    prefer-ip-address: true
    non-secure-port: 8787
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
